"""
Event-Driven Algorithmic Quantitative Trading Strategy Framework
================================================================
Architecture:
- FeatureEngine: Computes VWAP, ATR, and fits Hidden Markov Models (HMM) for regime detection.
- StrategyEngine: Generates 'Trade Intent' when market state is Trending and price bounces off VWAP.
- AIScoringEngine: Mock XGBoost ML scoring model returning conviction probability (0-100).
- RiskManagementEngine: Validates AI Score > 60, calculates position size via ATR fixed fractional model,
  and assigns dynamic Stop-Loss (1.5 * ATR) and Take-Profit (3.0 * ATR) levels.
"""

import sys
import math
import random
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime

# Optional imports for production numerical performance
try:
    import numpy as np
    import pandas as pd
    HAS_PANDAS_NUMPY = True
except ImportError:
    HAS_PANDAS_NUMPY = False

try:
    from hmmlearn.hmm import GaussianHMM
    HAS_HMMLEARN = True
except ImportError:
    HAS_HMMLEARN = False


# ============================================================================
# DATA STRUCTURES
# ============================================================================

@dataclass
class CandleTick:
    """Represents an incoming market tick/candle."""
    symbol: str
    timestamp: str
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class MarketFeatures:
    """Processed market features generated by FeatureEngine."""
    symbol: str
    timestamp: str
    current_price: float
    vwap: float
    atr: float
    regime_state: int      # 0 = Ranging, 1 = Trending
    regime_label: str      # 'Ranging' or 'Trending'
    price_vwap_diff: float


@dataclass
class TradeIntent:
    """Signal output from StrategyEngine."""
    symbol: str
    timestamp: str
    side: str              # 'BUY' or 'SELL'
    entry_price: float
    vwap: float
    atr: float
    regime: str
    reason: str


@dataclass
class ScoredTradeIntent:
    """Scored signal output from AIScoringEngine."""
    trade_intent: TradeIntent
    ai_score: float        # 0.0 - 100.0
    model_version: str


@dataclass
class ApprovedOrder:
    """Final risk-approved execution order output from RiskManagementEngine."""
    symbol: str
    side: str
    entry_price: float
    position_size: float
    stop_loss: float
    take_profit: float
    ai_score: float
    account_balance: float
    risk_amount_usdt: float
    status: str
    timestamp: str


# ============================================================================
# 1. FEATURE ENGINE
# ============================================================================

class FeatureEngine:
    """
    Ingests OHLCV candle data and computes:
    - VWAP (Volume-Weighted Average Price)
    - ATR (Average True Range)
    - Market Regime Detection via Hidden Markov Model (HMM)
    """

    def __init__(self, atr_period: int = 14, hmm_n_components: int = 2):
        self.atr_period = atr_period
        self.hmm_n_components = hmm_n_components
        self.history: List[CandleTick] = []
        self.hmm_model: Optional[Any] = None
        self.is_hmm_fitted = False

        if HAS_HMMLEARN:
            self.hmm_model = GaussianHMM(
                n_components=self.hmm_n_components,
                covariance_type="diag",
                n_iter=100,
                random_state=42
            )

    def update(self, candle: CandleTick) -> MarketFeatures:
        """Incorporate a new candle tick and recompute technical indicators & regime state."""
        self.history.append(candle)

        vwap = self._calculate_vwap()
        atr = self._calculate_atr()
        regime_state, regime_label = self._predict_regime()

        price_diff = candle.close - vwap

        return MarketFeatures(
            symbol=candle.symbol,
            timestamp=candle.timestamp,
            current_price=candle.close,
            vwap=round(vwap, 4),
            atr=round(atr, 4),
            regime_state=regime_state,
            regime_label=regime_label,
            price_vwap_diff=round(price_diff, 4)
        )

    def _calculate_vwap(self) -> float:
        """Calculates Volume-Weighted Average Price across available history."""
        if not self.history:
            return 0.0

        if HAS_PANDAS_NUMPY:
            closes = np.array([c.close for c in self.history])
            highs = np.array([c.high for c in self.history])
            lows = np.array([c.low for c in self.history])
            volumes = np.array([c.volume for c in self.history])

            typical_prices = (highs + lows + closes) / 3.0
            total_vol = np.sum(volumes)
            if total_vol == 0:
                return float(closes[-1])
            return float(np.sum(typical_prices * volumes) / total_vol)
        else:
            total_pv = 0.0
            total_vol = 0.0
            for c in self.history:
                tp = (c.high + c.low + c.close) / 3.0
                total_pv += tp * c.volume
                total_vol += c.volume
            return total_pv / total_vol if total_vol > 0 else self.history[-1].close

    def _calculate_atr(self) -> float:
        """Calculates Average True Range (ATR) over period."""
        if len(self.history) < 2:
            return max(self.history[-1].high - self.history[-1].low, 1.0) if self.history else 1.0

        tr_list = []
        for i in range(1, len(self.history)):
            curr = self.history[i]
            prev = self.history[i - 1]
            tr = max(
                curr.high - curr.low,
                abs(curr.high - prev.close),
                abs(curr.low - prev.close)
            )
            tr_list.append(tr)

        window = tr_list[-self.atr_period:]
        return sum(window) / len(window) if window else 1.0

    def _predict_regime(self) -> tuple[int, str]:
        """
        Fits/predicts current market regime using Gaussian HMM based on price returns and volatility.
        State 1 = Trending, State 0 = Ranging.
        """
        if len(self.history) < 10:
            return 1, "Trending"  # Default initial assumption

        returns = [
            (self.history[i].close - self.history[i-1].close) / self.history[i-1].close
            for i in range(1, len(self.history))
        ]

        if HAS_HMMLEARN and len(returns) >= 20:
            try:
                X = np.column_stack([returns])
                if not self.is_hmm_fitted:
                    self.hmm_model.fit(X)
                    self.is_hmm_fitted = True
                
                hidden_states = self.hmm_model.predict(X)
                latest_state = int(hidden_states[-1])
                label = "Trending" if latest_state == 1 else "Ranging"
                return latest_state, label
            except Exception:
                pass

        # Fallback Statistical Regime Classifier if hmmlearn is unavailable
        latest_return = returns[-1]
        recent_std = sum(abs(r) for r in returns[-10:]) / 10.0
        if abs(latest_return) > (0.7 * recent_std):
            return 1, "Trending"
        return 0, "Ranging"


# ============================================================================
# 2. STRATEGY ENGINE
# ============================================================================

class StrategyEngine:
    """
    Evaluates incoming MarketFeatures from FeatureEngine.
    Strategy Logic:
    - IF regime is 'Trending' (State 1)
    - AND price pulls back to and bounces off/crosses above VWAP
    - THEN generates a 'Trade Intent' signal (BUY).
    """

    def __init__(self, vwap_tolerance_pct: float = 0.003):
        self.vwap_tolerance_pct = vwap_tolerance_pct
        self.prev_features: Optional[MarketFeatures] = None

    def evaluate(self, features: MarketFeatures) -> Optional[TradeIntent]:
        """
        Evaluates market features for signal conditions.
        Returns TradeIntent object if conditions are satisfied, else None.
        """
        if self.prev_features is None:
            self.prev_features = features
            return None

        # Rule 1: Regime must be Trending
        is_trending = (features.regime_label == "Trending" or features.regime_state == 1)

        # Rule 2: VWAP Bounce/Cross detection
        # Price was near/below VWAP in previous candle and crossed above VWAP in current candle
        prev_p = self.prev_features.current_price
        prev_vwap = self.prev_features.vwap
        curr_p = features.current_price
        curr_vwap = features.vwap

        # Check if price bounced near VWAP (within tolerance) or crossed above VWAP
        distance_to_vwap = abs(curr_p - curr_vwap) / curr_vwap
        is_near_vwap = distance_to_vwap <= self.vwap_tolerance_pct
        is_vwap_crossover = (prev_p <= prev_vwap) and (curr_p > curr_vwap)
        is_vwap_bounce = is_near_vwap and (curr_p >= curr_vwap)

        self.prev_features = features

        if is_trending and (is_vwap_crossover or is_vwap_bounce):
            reason = "HMM Regime Trending + VWAP Cross/Bounce detected"
            return TradeIntent(
                symbol=features.symbol,
                timestamp=features.timestamp,
                side="BUY",
                entry_price=features.current_price,
                vwap=features.vwap,
                atr=features.atr,
                regime=features.regime_label,
                reason=reason
            )

        return None


# ============================================================================
# 3. AI SCORING ENGINE
# ============================================================================

class AIScoringEngine:
    """
    Evaluates 'Trade Intent' signals using a predictive ML model (mock XGBoost architecture).
    Returns a conviction probability score between 0 and 100.
    """

    def __init__(self, model_version: str = "XGBoost_v2.4_RegimeWeighted"):
        self.model_version = model_version

    def score_trade_intent(self, trade_intent: TradeIntent, features: MarketFeatures) -> ScoredTradeIntent:
        """
        Evaluates trade intent against market features to assign an AI conviction probability score.
        """
        # Mock XGBoost scoring logic evaluating momentum alignment and ATR ratio
        base_score = 50.0

        # Feature 1: Price distance from VWAP
        dist_from_vwap = (features.current_price - features.vwap) / features.vwap
        if 0.0 <= dist_from_vwap <= 0.005:
            base_score += 20.0  # Perfect sweet-spot bounce
        elif dist_from_vwap > 0.01:
            base_score -= 10.0  # Overextended

        # Feature 2: Regime alignment
        if features.regime_label == "Trending":
            base_score += 18.0

        # Feature 3: Volatility sanity check (ATR ratio)
        atr_pct = features.atr / features.current_price
        if 0.001 <= atr_pct <= 0.02:
            base_score += 12.0

        # Random micro-variance representing model feature interactions
        micro_variance = random.uniform(-3.0, 5.0)
        final_score = round(min(max(base_score + micro_variance, 0.0), 100.0), 1)

        return ScoredTradeIntent(
            trade_intent=trade_intent,
            ai_score=final_score,
            model_version=self.model_version
        )


# ============================================================================
# 4. RISK MANAGEMENT ENGINE
# ============================================================================

class RiskManagementEngine:
    """
    Receives ScoredTradeIntent and enforces risk parameters:
    - Validates AI Score > 60.0.
    - Calculates position size using Fixed Fractional Risk Model:
        Position_Size = (Account_Balance * 0.01) / ATR
    - Sets dynamic Stop-Loss at 1.5 * ATR below entry price.
    - Sets Take-Profit at 3.0 * ATR above entry price.
    """

    def __init__(self, min_ai_threshold: float = 60.0, risk_fraction: float = 0.01):
        self.min_ai_threshold = min_ai_threshold
        self.risk_fraction = risk_fraction  # 1% per trade

    def process_scored_intent(
        self,
        scored_intent: ScoredTradeIntent,
        account_balance: float = 10000.0
    ) -> Optional[ApprovedOrder]:
        """
        Validates AI score threshold and calculates position sizing & SL/TP levels.
        """
        intent = scored_intent.trade_intent
        ai_score = scored_intent.ai_score

        if ai_score <= self.min_ai_threshold:
            print(f"  [RISK REJECTED] AI Score {ai_score} <= threshold {self.min_ai_threshold}. Trade aborted.")
            return None

        # Fixed Fractional Sizing calculation
        risk_amount_usdt = account_balance * self.risk_fraction
        atr = max(intent.atr, 0.1)
        position_size = round(risk_amount_usdt / atr, 4)

        # SL and TP calculation
        stop_loss = round(intent.entry_price - (1.5 * atr), 4)
        take_profit = round(intent.entry_price + (3.0 * atr), 4)

        return ApprovedOrder(
            symbol=intent.symbol,
            side=intent.side,
            entry_price=intent.entry_price,
            position_size=position_size,
            stop_loss=stop_loss,
            take_profit=take_profit,
            ai_score=ai_score,
            account_balance=account_balance,
            risk_amount_usdt=risk_amount_usdt,
            status="APPROVED_AND_READY",
            timestamp=intent.timestamp
        )


# ============================================================================
# SEQUENTIAL DEMONSTRATION PIPELINE
# ============================================================================

def run_pipeline_demo():
    """
    Demonstrates sequential event handling when market ticks/candles arrive.
    """
    print("=" * 80)
    print("   QUANTITATIVE EVENT-DRIVEN TRADING FRAMEWORK")
    print("   HMM Regime Detection | VWAP Pullback | XGBoost AI Score | ATR Risk")
    print("=" * 80)

    # 1. Instantiate Core Engine Pipeline
    feature_engine = FeatureEngine(atr_period=14)
    strategy_engine = StrategyEngine(vwap_tolerance_pct=0.005)
    ai_scoring_engine = AIScoringEngine()
    risk_engine = RiskManagementEngine(min_ai_threshold=60.0, risk_fraction=0.01)

    account_balance = 10000.0  # 10,000 USDT Account

    # 2. Simulate Incoming Candle Stream (BTC/USDT 15m candles)
    base_price = 66000.0
    candle_stream = []
    
    # Generate 15 simulated sequential candles exhibiting a VWAP pullback & bounce
    prices = [
        66000, 66100, 66250, 66400, 66350,
        66200, 66150, 66080, 66020, 66050,  # Pullback towards VWAP
        66180, 66320, 66500, 66700, 66850   # Strong VWAP bounce & breakout
    ]

    for i, close in enumerate(prices, 1):
        high = close + random.uniform(20, 80)
        low = close - random.uniform(20, 80)
        open_p = close - random.uniform(-30, 30)
        volume = random.uniform(100, 500)
        ts = f"2026-07-22T04:{i:02d}:00Z"
        candle_stream.append(CandleTick("BTC/USDT", ts, open_p, high, low, close, volume))

    print(f"\n[STREAM INITIATED] Processing {len(candle_stream)} sequential market candles...\n")

    # 3. Process Candles Sequentially Through Event Pipeline
    for tick in candle_stream:
        # Step A: Feature Processing & Indicator Calculation
        features = feature_engine.update(tick)

        print(f"[{tick.timestamp}] Candle Close: ${tick.close:,.2f} | VWAP: ${features.vwap:,.2f} | ATR: ${features.atr:,.2f} | Regime: {features.regime_label}")

        # Step B: Strategy Signal Evaluation
        trade_intent = strategy_engine.evaluate(features)

        if trade_intent:
            print(f"\n  🎯 [TRADE INTENT TRIGGERED] Side: {trade_intent.side} @ ${trade_intent.entry_price:,.2f}")
            print(f"     Reason: {trade_intent.reason}")

            # Step C: AI Scoring Model Evaluation
            scored_intent = ai_scoring_engine.score_trade_intent(trade_intent, features)
            print(f"  🧠 [AI SCORING ENGINE] Model: {scored_intent.model_version} | Conviction Score: {scored_intent.ai_score}/100")

            # Step D: Risk Management & Order Allocation
            approved_order = risk_engine.process_scored_intent(scored_intent, account_balance=account_balance)

            if approved_order:
                print(f"  ✅ [RISK APPROVED ORDER]")
                print(f"     • Symbol: {approved_order.symbol}")
                print(f"     • Position Size: {approved_order.position_size} BTC (1% Risk = ${approved_order.risk_amount_usdt:.2f})")
                print(f"     • Entry Price: ${approved_order.entry_price:,.2f}")
                print(f"     • Stop Loss (1.5x ATR): ${approved_order.stop_loss:,.2f}")
                print(f"     • Take Profit (3.0x ATR): ${approved_order.take_profit:,.2f}")
                print(f"     • Status: {approved_order.status}\n")

    print("=" * 80)
    print("   EVENT-DRIVEN PIPELINE SIMULATION COMPLETED")
    print("=" * 80)


if __name__ == "__main__":
    run_pipeline_demo()
